#include <windows.h>
#include <GL/gl.h>
#include <stdint.h>
#include <stdio.h>
#define VS 0x8b31
#define FS 0x8b30
#define COMPILE 0x8b81
#define LINK 0x8b82
#define UBO 0x8a11
#define STATIC_DRAW 0x88e4
#define TRIANGLES 4
typedef GLuint(WINAPI*CS)(GLenum);typedef void(WINAPI*SS)(GLuint,GLsizei,const char*const*,const GLint*);typedef void(WINAPI*CO)(GLuint);typedef void(WINAPI*SI)(GLuint,GLenum,GLint*);typedef GLuint(WINAPI*CP)(void);typedef void(WINAPI*AT)(GLuint,GLuint);typedef void(WINAPI*LI)(GLuint);typedef void(WINAPI*PI)(GLuint,GLenum,GLint*);typedef void(WINAPI*US)(GLuint);typedef void(WINAPI*GB)(GLsizei,GLuint*);typedef void(WINAPI*CB)(GLsizei,GLuint*);typedef void(WINAPI*BB)(GLenum,GLuint);typedef void(WINAPI*BD)(GLenum,intptr_t,const void*,GLenum);typedef void(WINAPI*BS)(GLenum,intptr_t,const void*,GLbitfield);typedef void(WINAPI*BP)(GLenum,GLenum,GLint*);typedef void(WINAPI*BBA)(GLenum,GLuint,GLuint);typedef GLuint(WINAPI*UBI)(GLuint,const char*);typedef void(WINAPI*UBB)(GLuint,GLuint,GLuint);typedef void(WINAPI*UBIV)(GLuint,GLuint,GLenum,GLint*);typedef void(WINAPI*UBN)(GLuint,GLuint,GLsizei,GLint*,char*);typedef void(WINAPI*BR)(GLenum,GLuint,GLuint,intptr_t,intptr_t);typedef void(WINAPI*NS)(GLuint,intptr_t,const void*,GLbitfield);
static void*p(const char*n){PROC q=wglGetProcAddress(n);HMODULE m;if(q)return(void*)q;m=GetModuleHandleA("opengl32.dll");return m?(void*)GetProcAddress(m,n):0;}
#define L(t,v,n)do{v=(t)p(n);if(!v){printf("FAIL missing %s\n",n);return 14;}}while(0)
int main(void){static const char vs[]="#version 450 core\nconst vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));void main(){gl_Position=vec4(p[gl_VertexID],0,1);}";static const char fs[]="#version 450 core\nlayout(std140,binding=0) uniform Data{vec4 tint;};out vec4 c;void main(){c=tint;}";static const float ubo_data[8]={0,0,0,0,.2f,.4f,.6f,1};PIXELFORMATDESCRIPTOR d={0};HWND w;HDC dc;HGLRC c;int pf;GLuint v,f,pr,b;GLint ok;CB cb;NS ns;unsigned char px[4]={0};CS cs;SS ss;CO co;SI si;CP cp;AT at;LI li;PI pi;US us;GB gb;BB bb;BD bd;BS bs;BP bp;BBA bba;BR br;UBI ubi;UBB ubb;UBIV ubiv;UBN ubn;w=CreateWindowA("STATIC","WineMetalGL UBO",WS_OVERLAPPEDWINDOW,0,0,64,64,0,0,0,0);if(!w)return 11;dc=GetDC(w);d.nSize=sizeof(d);d.nVersion=1;d.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL;d.iPixelType=PFD_TYPE_RGBA;d.cColorBits=32;pf=ChoosePixelFormat(dc,&d);if(!pf||!SetPixelFormat(dc,pf,&d))return 12;c=wglCreateContext(dc);if(!c||!wglMakeCurrent(dc,c))return 13;L(CS,cs,"glCreateShader");L(SS,ss,"glShaderSource");L(CO,co,"glCompileShader");L(SI,si,"glGetShaderiv");L(CP,cp,"glCreateProgram");L(AT,at,"glAttachShader");L(LI,li,"glLinkProgram");L(PI,pi,"glGetProgramiv");L(US,us,"glUseProgram");L(GB,gb,"glGenBuffers");L(CB,cb,"glCreateBuffers");L(BB,bb,"glBindBuffer");L(BD,bd,"glBufferData");L(BS,bs,"glBufferStorage");L(NS,ns,"glNamedBufferStorage");L(BP,bp,"glGetBufferParameteriv");L(BBA,bba,"glBindBufferBase");L(BR,br,"glBindBufferRange");L(UBI,ubi,"glGetUniformBlockIndex");L(UBB,ubb,"glUniformBlockBinding");L(UBIV,ubiv,"glGetActiveUniformBlockiv");L(UBN,ubn,"glGetActiveUniformBlockName");v=cs(VS);f=cs(FS);{const char*x=vs;ss(v,1,&x,0);}{const char*x=fs;ss(f,1,&x,0);}co(v);co(f);si(v,COMPILE,&ok);if(!ok)return 15;si(f,COMPILE,&ok);if(!ok)return 16;pr=cp();at(pr,v);at(pr,f);li(pr);pi(pr,LINK,&ok);if(!ok)return 17;us(pr);GLuint block=ubi(pr,"Data"); if(block==0xffffffffu)return 18; ubb(pr,block,0); GLint block_size=0;ubiv(pr,block,0x8A40,&block_size);char block_name[16]={0};GLint block_name_len=0;ubn(pr,block,sizeof(block_name),&block_name_len,block_name);if(block_size!=16||block_name_len!=4)return 18;printf("WINEMETALGL_UBO_REFLECTION_OK\n");cb(1,&b);ns(b,sizeof(ubo_data),ubo_data,0);bb(UBO,b);GLint buffer_size=0;bp(UBO,0x8764,&buffer_size);if(buffer_size!=(GLint)sizeof(ubo_data))return 18;printf("WINEMETALGL_BUFFER_SIZE_OK\n");br(UBO,0,b,sizeof(float)*4,sizeof(float)*4);printf("WINEMETALGL_UBO_RANGE_OK\n");glViewport(0,0,64,64);glDrawArrays(TRIANGLES,0,3);glReadPixels(32,32,1,1,GL_RGBA,GL_UNSIGNED_BYTE,px);printf("UBO rgba=%u,%u,%u,%u error=0x%x\n",px[0],px[1],px[2],px[3],(unsigned)glGetError());if(px[0]<47||px[0]>55||px[1]<98||px[1]>106||px[2]<149||px[2]>157||px[3]<250)return 18;printf("WINEMETALGL_UBO_OK\n");wglMakeCurrent(0,0);wglDeleteContext(c);ReleaseDC(w,dc);DestroyWindow(w);return 0;}
