#include <windows.h>
#include <GL/gl.h>
#include <stdio.h>
#include <stdint.h>
#define ARRAY_BUFFER 0x8892
#define STATIC_DRAW 0x88E4
typedef void(WINAPI*GB)(GLsizei,GLuint*);typedef void(WINAPI*BB)(GLenum,GLuint);typedef void(WINAPI*BD)(GLenum,intptr_t,const void*,GLenum);typedef void(WINAPI*EA)(GLuint);typedef void(WINAPI*VP)(GLuint,GLint,GLenum,GLboolean,GLsizei,const void*);typedef GLuint(WINAPI*CS)(GLenum);typedef void(WINAPI*SS)(GLuint,GLsizei,const char*const*,const GLint*);typedef void(WINAPI*CO)(GLuint);typedef void(WINAPI*SI)(GLuint,GLenum,GLint*);typedef GLuint(WINAPI*CP)(void);typedef void(WINAPI*AT)(GLuint,GLuint);typedef void(WINAPI*LI)(GLuint);typedef void(WINAPI*PI)(GLuint,GLenum,GLint*);typedef void(WINAPI*US)(GLuint);typedef void(WINAPI*DA)(GLenum,GLint,GLsizei);
static void*p(const char*n){PROC q=wglGetProcAddress(n);HMODULE m;if(q)return(void*)q;m=GetModuleHandleA("opengl32.dll");return m?(void*)GetProcAddress(m,n):0;}
#define L(t,v,n)do{v=(t)p(n);if(!v){printf("FAIL missing %s\n",n);return 14;}}while(0)
int main(void){static const char vs[]="#version 120\nattribute vec2 position;varying vec4 color;void main(){gl_Position=vec4(position,0,1);color=vec4(.2,.4,.6,1);}";static const char fs[]="#version 120\nvarying vec4 color;void main(){gl_FragColor=color;}";static const float vertices[]={-1,-1,3,-1,-1,3};PIXELFORMATDESCRIPTOR d={0};HWND w;HDC dc;HGLRC c;int pf;GLuint v,f,pr;GLint ok;unsigned char px[4]={0};GB gen_buffers;BB bind_buffer;BD buffer_data;EA enable_attrib;VP attrib_pointer;CS cs;SS ss;CO co;SI si;CP cp;AT at;LI li;PI pi;US us;DA draw;w=CreateWindowA("STATIC","WineMetalGL GLSL120",WS_OVERLAPPEDWINDOW,0,0,64,64,0,0,0,0);if(!w)return 11;dc=GetDC(w);d.nSize=sizeof(d);d.nVersion=1;d.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL;d.iPixelType=PFD_TYPE_RGBA;d.cColorBits=32;pf=ChoosePixelFormat(dc,&d);if(!pf||!SetPixelFormat(dc,pf,&d))return 12;c=wglCreateContext(dc);if(!c||!wglMakeCurrent(dc,c))return 13;L(GB,gen_buffers,"glGenBuffers");L(BB,bind_buffer,"glBindBuffer");L(BD,buffer_data,"glBufferData");L(EA,enable_attrib,"glEnableVertexAttribArray");L(VP,attrib_pointer,"glVertexAttribPointer");L(CS,cs,"glCreateShader");L(SS,ss,"glShaderSource");L(CO,co,"glCompileShader");L(SI,si,"glGetShaderiv");L(CP,cp,"glCreateProgram");L(AT,at,"glAttachShader");L(LI,li,"glLinkProgram");L(PI,pi,"glGetProgramiv");L(US,us,"glUseProgram");L(DA,draw,"glDrawArrays");v=cs(0x8B31);f=cs(0x8B30);{const char*x=vs;ss(v,1,&x,0);}{const char*x=fs;ss(f,1,&x,0);}co(v);co(f);si(v,0x8B81,&ok);if(!ok)return 15;si(f,0x8B81,&ok);if(!ok)return 16;pr=cp();at(pr,v);at(pr,f);li(pr);pi(pr,0x8B82,&ok);if(!ok)return 17;us(pr);GLuint buffer=0;gen_buffers(1,&buffer);bind_buffer(ARRAY_BUFFER,buffer);buffer_data(ARRAY_BUFFER,sizeof(vertices),vertices,STATIC_DRAW);glViewport(0,0,64,64);enable_attrib(0);attrib_pointer(0,2,GL_FLOAT,GL_FALSE,2*sizeof(float),(const void*)0);draw(GL_TRIANGLES,0,3);glReadPixels(32,32,1,1,GL_RGBA,GL_UNSIGNED_BYTE,px);printf("GLSL120 rgba=%u,%u,%u,%u error=0x%x\n",px[0],px[1],px[2],px[3],(unsigned)glGetError());if(px[0]<47||px[0]>55||px[1]<98||px[1]>106||px[2]<149||px[2]>157||px[3]<250)return 18;printf("WINEMETALGL_GLSL120_OK\n");wglMakeCurrent(0,0);wglDeleteContext(c);ReleaseDC(w,dc);DestroyWindow(w);return 0;}
