#include <windows.h>
#include <GL/gl.h>
#include <stdio.h>
#define VS 0x8B31
#define FS 0x8B30
#define COMPILE 0x8B81
#define LINK_STATUS 0x8B82
#define RECT 0x84F5
#define RGBA 0x1908
#define UBYTE 0x1401
typedef GLuint(WINAPI*CS)(GLenum);typedef void(WINAPI*SS)(GLuint,GLsizei,const char*const*,const GLint*);typedef void(WINAPI*CO)(GLuint);typedef void(WINAPI*SI)(GLuint,GLenum,GLint*);typedef GLuint(WINAPI*CP)(void);typedef void(WINAPI*AT)(GLuint,GLuint);typedef void(WINAPI*LI)(GLuint);typedef void(WINAPI*PI)(GLuint,GLenum,GLint*);typedef void(WINAPI*US)(GLuint);typedef GLint(WINAPI*UL)(GLuint,const char*);typedef void(WINAPI*U1)(GLint,GLint);typedef void(WINAPI*GT)(GLsizei,GLuint*);typedef void(WINAPI*BT)(GLenum,GLuint);typedef void(WINAPI*TP)(GLenum,GLenum,GLint);typedef void(WINAPI*TI)(GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const void*);typedef void(WINAPI*DA)(GLenum,GLint,GLsizei);typedef void(WINAPI*GX)(GLenum,GLint,GLenum,GLenum,void*);
static void*p(const char*n){PROC q=wglGetProcAddress(n);HMODULE m;if(q)return(void*)q;m=GetModuleHandleA("opengl32.dll");return m?(void*)GetProcAddress(m,n):0;}
#define L(t,v,n)do{v=(t)p(n);if(!v){printf("FAIL missing %s\n",n);return 14;}}while(0)
int main(void){static const char vs[]="#version 330 core\nconst vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));void main(){gl_Position=vec4(p[gl_VertexID],0,1);}";static const char fs[]="#version 330 core\nuniform sampler2DRect tex;out vec4 color;void main(){color=texture(tex,vec2(.5,.5));}";static const unsigned char red[16]={255,0,0,255,255,0,0,255,255,0,0,255,255,0,0,255};PIXELFORMATDESCRIPTOR d={0};HWND w;HDC dc;HGLRC c;int pf;GLuint v,f,pr,tex;GLint ok;unsigned char px[4]={0},raw[16]={0};CS cs;SS ss;CO co;SI si;CP cp;AT at;LI li;PI pi;US us;UL ul;U1 u1;GT gt;BT bt;TP tp;TI ti;DA draw;GX getx;w=CreateWindowA("STATIC","WineMetalGL rectangle",WS_OVERLAPPEDWINDOW,0,0,64,64,0,0,0,0);if(!w)return 11;dc=GetDC(w);d.nSize=sizeof(d);d.nVersion=1;d.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL;d.iPixelType=PFD_TYPE_RGBA;d.cColorBits=32;pf=ChoosePixelFormat(dc,&d);if(!pf||!SetPixelFormat(dc,pf,&d))return 12;c=wglCreateContext(dc);if(!c||!wglMakeCurrent(dc,c))return 13;L(CS,cs,"glCreateShader");L(SS,ss,"glShaderSource");L(CO,co,"glCompileShader");L(SI,si,"glGetShaderiv");L(CP,cp,"glCreateProgram");L(AT,at,"glAttachShader");L(LI,li,"glLinkProgram");L(PI,pi,"glGetProgramiv");L(US,us,"glUseProgram");L(UL,ul,"glGetUniformLocation");L(U1,u1,"glUniform1i");L(GT,gt,"glGenTextures");L(BT,bt,"glBindTexture");L(TP,tp,"glTexParameteri");L(TI,ti,"glTexImage2D");L(DA,draw,"glDrawArrays");L(GX,getx,"glGetTexImage");v=cs(VS);f=cs(FS);{const char*x=vs;ss(v,1,&x,0);}{const char*x=fs;ss(f,1,&x,0);}co(v);co(f);si(v,COMPILE,&ok);if(!ok)return 15;si(f,COMPILE,&ok);if(!ok)return 16;pr=cp();at(pr,v);at(pr,f);li(pr);pi(pr,LINK_STATUS,&ok);if(!ok)return 17;us(pr);u1(ul(pr,"tex"),0);gt(1,&tex);bt(RECT,tex);tp(RECT,0x2801,0x2600);tp(RECT,0x2800,0x2600);ti(RECT,0,GL_RGBA,2,2,0,RGBA,UBYTE,red);getx(RECT,0,RGBA,UBYTE,raw);if(raw[0]!=255||raw[1]!=0||raw[2]!=0||raw[3]!=255)return 18;glViewport(0,0,64,64);draw(GL_TRIANGLES,0,3);glReadPixels(32,32,1,1,RGBA,UBYTE,px);printf("Rectangle rgba=%u,%u,%u,%u error=0x%x\n",px[0],px[1],px[2],px[3],(unsigned)glGetError());if(px[0]<250||px[1]>5||px[2]>5||px[3]<250)return 19;printf("WINEMETALGL_TEXTURE_RECTANGLE_OK\n");wglMakeCurrent(0,0);wglDeleteContext(c);ReleaseDC(w,dc);DestroyWindow(w);return 0;}
