#include <windows.h>
#include <GL/gl.h>
#include <stdio.h>
#define VS 0x8b31
#define FS 0x8b30
#define COMPILE 0x8b81
#define LINK 0x8b82
#define PROGRAM_SEPARABLE 0x8258
#define VERTEX_SHADER_BIT 0x00000001
#define FRAGMENT_SHADER_BIT 0x00000002
typedef GLuint(WINAPI*CS)(GLenum);typedef void(WINAPI*SS)(GLuint,GLsizei,const char*const*,const GLint*);typedef void(WINAPI*CO)(GLuint);typedef void(WINAPI*SI)(GLuint,GLenum,GLint*);typedef GLuint(WINAPI*CP)(void);typedef void(WINAPI*AT)(GLuint,GLuint);typedef void(WINAPI*LI)(GLuint);typedef void(WINAPI*PI)(GLuint,GLenum,GLint*);typedef void(WINAPI*PP)(GLuint,GLenum,GLint);typedef void(WINAPI*GP)(GLsizei,GLuint*);typedef void(WINAPI*DP)(GLsizei,const GLuint*);typedef void(WINAPI*BP)(GLuint);typedef void(WINAPI*USP)(GLuint);typedef void(WINAPI*UP)(GLuint,GLbitfield,GLuint);typedef void(WINAPI*VP)(GLuint,GLenum,GLint*);typedef GLint(WINAPI*GUL)(GLuint,const char*);typedef void(WINAPI*PU4)(GLuint,GLint,GLfloat,GLfloat,GLfloat,GLfloat);typedef GLboolean(WINAPI*ISP)(GLuint);
static void*p(const char*n){PROC q=wglGetProcAddress(n);HMODULE m;if(q)return(void*)q;m=GetModuleHandleA("opengl32.dll");return m?(void*)GetProcAddress(m,n):0;}
#define L(t,v,n)do{v=(t)p(n);if(!v){printf("FAIL missing %s\n",n);return 14;}}while(0)
int main(void){static const char vs[]="#version 330 core\nconst vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));void main(){gl_Position=vec4(p[gl_VertexID],0,1);}";static const char fs[]="#version 330 core\nuniform vec4 tint;out vec4 color;void main(){color=tint;}";PIXELFORMATDESCRIPTOR d={0};HWND w;HDC dc;HGLRC c;int pf;GLuint sv,sf,pv,pfprog,pipeline;GLint ok;unsigned char pixel[4]={0};CS cs;SS ss;CO co;SI si;CP cp;AT at;LI li;PI pi;PP pp;GP gp;DP delpipe;BP bindpipe;USP use_program;UP use_stages;VP getpipe;GUL get_uniform;PU4 program_uniform4f;ISP ispipe;w=CreateWindowA("STATIC","WineMetalGL pipeline",WS_OVERLAPPEDWINDOW,0,0,64,64,0,0,0,0);if(!w)return 11;dc=GetDC(w);d.nSize=sizeof(d);d.nVersion=1;d.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL;d.iPixelType=PFD_TYPE_RGBA;d.cColorBits=32;pf=ChoosePixelFormat(dc,&d);if(!pf||!SetPixelFormat(dc,pf,&d))return 12;c=wglCreateContext(dc);if(!c||!wglMakeCurrent(dc,c))return 13;L(CS,cs,"glCreateShader");L(SS,ss,"glShaderSource");L(CO,co,"glCompileShader");L(SI,si,"glGetShaderiv");L(CP,cp,"glCreateProgram");L(AT,at,"glAttachShader");L(LI,li,"glLinkProgram");L(PI,pi,"glGetProgramiv");L(PP,pp,"glProgramParameteri");L(GP,gp,"glGenProgramPipelines");L(DP,delpipe,"glDeleteProgramPipelines");L(BP,bindpipe,"glBindProgramPipeline");L(USP,use_program,"glUseProgram");L(UP,use_stages,"glUseProgramStages");L(VP,getpipe,"glGetProgramPipelineiv");L(ISP,ispipe,"glIsProgramPipeline");L(GUL,get_uniform,"glGetUniformLocation");L(PU4,program_uniform4f,"glProgramUniform4f");sv=cs(VS);sf=cs(FS);{const char*s=vs;ss(sv,1,&s,0);}{const char*s=fs;ss(sf,1,&s,0);}co(sv);co(sf);si(sv,COMPILE,&ok);if(!ok)return 15;si(sf,COMPILE,&ok);if(!ok)return 16;pv=cp();at(pv,sv);pp(pv,PROGRAM_SEPARABLE,1);li(pv);pi(pv,LINK,&ok);if(!ok)return 17;pfprog=cp();at(pfprog,sf);pp(pfprog,PROGRAM_SEPARABLE,1);li(pfprog);pi(pfprog,LINK,&ok);if(!ok)return 18;GLint tint=get_uniform(pfprog,"tint");if(tint<0)return 18;program_uniform4f(pfprog,tint,.2f,.4f,.6f,1.f);gp(1,&pipeline);if(!ispipe(pipeline))return 19;use_stages(pipeline,VERTEX_SHADER_BIT,pv);use_stages(pipeline,FRAGMENT_SHADER_BIT,pfprog);bindpipe(pipeline);getpipe(pipeline,LINK,&ok);if(!ok)return 20;printf("WINEMETALGL_PROGRAM_PIPELINE_OK\n");use_program(0);glViewport(0,0,64,64);glDrawArrays(GL_TRIANGLES,0,3);glReadPixels(32,32,1,1,GL_RGBA,GL_UNSIGNED_BYTE,pixel);if(pixel[0]<47||pixel[0]>55||pixel[1]<98||pixel[1]>106||pixel[2]<149||pixel[2]>157||pixel[3]<245)return 21;printf("WINEMETALGL_PROGRAM_PIPELINE_DRAW_OK\n");delpipe(1,&pipeline);wglMakeCurrent(0,0);wglDeleteContext(c);ReleaseDC(w,dc);DestroyWindow(w);return 0;}
