#include <windows.h>
#include <GL/gl.h>
#include <stdint.h>
#include <stdio.h>
#define VS 0x8b31
#define FS 0x8b30
#define COMPILE 0x8b81
#define LINK 0x8b82
#define TEX3D 0x806f
#define RGBA 0x1908
#define UBYTE 0x1401
#define LINEAR 0x2601
#define TRIANGLES 4
typedef GLuint(WINAPI*CS)(GLenum);typedef void(WINAPI*SS)(GLuint,GLsizei,const char*const*,const GLint*);typedef void(WINAPI*CO)(GLuint);typedef void(WINAPI*SI)(GLuint,GLenum,GLint*);typedef GLuint(WINAPI*CP)(void);typedef void(WINAPI*AT)(GLuint,GLuint);typedef void(WINAPI*LI)(GLuint);typedef void(WINAPI*PI)(GLuint,GLenum,GLint*);typedef void(WINAPI*US)(GLuint);typedef void(WINAPI*GENT)(GLsizei,GLuint*);typedef void(WINAPI*CT)(GLenum,GLsizei,GLuint*);typedef void(WINAPI*TSG)(GLuint,GLsizei,GLenum,GLsizei,GLsizei,GLsizei);typedef void(WINAPI*TSS3)(GLuint,GLint,GLint,GLint,GLint,GLsizei,GLsizei,GLsizei,GLenum,GLenum,const void*);typedef void(WINAPI*BT)(GLenum,GLuint);typedef void(WINAPI*TP)(GLenum,GLenum,GLint);typedef void(WINAPI*TI3)(GLenum,GLint,GLint,GLsizei,GLsizei,GLsizei,GLint,GLenum,GLenum,const void*);typedef void(WINAPI*GETI)(GLenum,GLint,GLenum,GLenum,void*);typedef void(WINAPI*TS3)(GLenum,GLint,GLint,GLint,GLint,GLsizei,GLsizei,GLsizei,GLenum,GLenum,const void*);
static void*p(const char*n){PROC q=wglGetProcAddress(n);HMODULE m;if(q)return(void*)q;m=GetModuleHandleA("opengl32.dll");return m?(void*)GetProcAddress(m,n):0;}
#define L(t,v,n)do{v=(t)p(n);if(!v){printf("FAIL missing %s\n",n);return 14;}}while(0)
int main(void){static const char vs[]="#version 330 core\nconst vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));void main(){gl_Position=vec4(p[gl_VertexID],0,1);}";static const char fs[]="#version 330 core\nuniform sampler3D tex;out vec4 c;void main(){c=texture(tex,vec3(.5));}";static const unsigned char data[2*2*2*4]={51,102,153,255,51,102,153,255,51,102,153,255,51,102,153,255,51,102,153,255,51,102,153,255,51,102,153,255,51,102,153,255};PIXELFORMATDESCRIPTOR d={0};HWND w;HDC dc;HGLRC c;int pf;GLuint v,f,pr,t;GLint ok,loc;TS3 ts;GETI get_tex_image;CT create_textures;TSG texture_storage;TSS3 texture_subimage;unsigned char px[4]={0};CS cs;SS ss;CO co;SI si;CP cp;AT at;LI li;PI pi;US us;GENT gen_textures;BT bt;TP tp;TI3 ti;w=CreateWindowA("STATIC","WineMetalGL 3D texture",WS_OVERLAPPEDWINDOW,0,0,64,64,0,0,0,0);if(!w)return 11;dc=GetDC(w);d.nSize=sizeof(d);d.nVersion=1;d.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL;d.iPixelType=PFD_TYPE_RGBA;d.cColorBits=32;pf=ChoosePixelFormat(dc,&d);if(!pf||!SetPixelFormat(dc,pf,&d))return 12;c=wglCreateContext(dc);if(!c||!wglMakeCurrent(dc,c))return 13;L(CS,cs,"glCreateShader");L(SS,ss,"glShaderSource");L(CO,co,"glCompileShader");L(SI,si,"glGetShaderiv");L(CP,cp,"glCreateProgram");L(AT,at,"glAttachShader");L(LI,li,"glLinkProgram");L(PI,pi,"glGetProgramiv");L(US,us,"glUseProgram");L(GENT,gen_textures,"glGenTextures");L(CT,create_textures,"glCreateTextures");L(TSG,texture_storage,"glTextureStorage3D");L(TSS3,texture_subimage,"glTextureSubImage3D");L(BT,bt,"glBindTexture");L(TP,tp,"glTexParameteri");L(TI3,ti,"glTexImage3D");L(TS3,ts,"glTexSubImage3D");L(GETI,get_tex_image,"glGetTexImage");v=cs(VS);f=cs(FS);{const char*x=vs;ss(v,1,&x,0);}{const char*x=fs;ss(f,1,&x,0);}co(v);co(f);si(v,COMPILE,&ok);if(!ok)return 15;si(f,COMPILE,&ok);if(!ok)return 16;pr=cp();at(pr,v);at(pr,f);li(pr);pi(pr,LINK,&ok);if(!ok)return 17;us(pr);create_textures(TEX3D,1,&t);texture_storage(t,1,0x8058,2,2,2);texture_subimage(t,0,0,0,0,2,2,2,RGBA,UBYTE,data);bt(TEX3D,t);tp(TEX3D,0x2801,LINEAR);tp(TEX3D,0x2800,LINEAR);unsigned char readback[32]={0};get_tex_image(TEX3D,0,RGBA,UBYTE,readback);printf("DSA 3D read=%u,%u,%u,%u err=0x%x\n",readback[0],readback[1],readback[2],readback[3],(unsigned)glGetError());if(readback[0]!=51||readback[1]!=102||readback[2]!=153||readback[3]!=255)return 18;loc=((GLint(WINAPI*)(GLuint,const char*))p("glGetUniformLocation"))(pr,"tex");((void(WINAPI*)(GLint,GLint))p("glUniform1i"))(loc,0);glViewport(0,0,64,64);glDrawArrays(TRIANGLES,0,3);glReadPixels(32,32,1,1,RGBA,UBYTE,px);printf("3D texture rgba=%u,%u,%u,%u error=0x%x\n",px[0],px[1],px[2],px[3],(unsigned)glGetError());if(px[0]<47||px[0]>55||px[1]<98||px[1]>106||px[2]<149||px[2]>157||px[3]<250)return 18;printf("WINEMETALGL_TEXTURE3D_OK\n");wglMakeCurrent(0,0);wglDeleteContext(c);ReleaseDC(w,dc);DestroyWindow(w);return 0;}
