#include <windows.h>
#include <GL/gl.h>
#include <stdio.h>

#define VS 0x8b31
#define FS 0x8b30
#define COMPILE 0x8b81
#define LINK 0x8b82
#define TRIANGLES 4

typedef GLuint(WINAPI *CS)(GLenum);typedef void(WINAPI *SS)(GLuint,GLsizei,const char*const*,const GLint*);typedef void(WINAPI *CO)(GLuint);typedef void(WINAPI *SI)(GLuint,GLenum,GLint*);typedef GLuint(WINAPI *CP)(void);typedef void(WINAPI *AT)(GLuint,GLuint);typedef void(WINAPI *LI)(GLuint);typedef void(WINAPI *PI)(GLuint,GLenum,GLint*);typedef void(WINAPI *US)(GLuint);typedef GLint(WINAPI *UL)(GLuint,const char*);typedef void(WINAPI *UM)(GLint,GLsizei,GLboolean,const GLfloat*);typedef void(WINAPI *GU)(GLuint,GLint,GLfloat*);typedef void(WINAPI *DA)(GLenum,GLint,GLint);
static void*p(const char*n){PROC q=wglGetProcAddress(n);HMODULE m=GetModuleHandleA("opengl32.dll");return q?(void*)q:(m?(void*)GetProcAddress(m,n):0);}
#define L(t,v,n)do{v=(t)p(n);if(!v){printf("FAIL missing %s\n",n);return 14;}}while(0)
int main(void){static const char vs[]="#version 330 core\nuniform mat4 transforms[2];const vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));void main(){gl_Position=transforms[0]*vec4(p[gl_VertexID],0,1);}";static const char fs[]="#version 330 core\nout vec4 color;void main(){color=vec4(.2,.4,.6,1);}";static const float matrices[32]={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,2,0,0,0,0,2,0,0,0,0,2,0,0,0,0,1};PIXELFORMATDESCRIPTOR d={0};HWND w;HDC dc;HGLRC c;int pf;GLuint v,f,pr;GLint ok;unsigned char px[4]={0};CS cs;SS ss;CO co;SI si;CP cp;AT at;LI li;PI pi;US us;UL ul;UM um;GU gu;DA draw;w=CreateWindowA("STATIC","WineMetalGL uniform matrix",WS_OVERLAPPEDWINDOW,0,0,64,64,0,0,0,0);if(!w)return 11;dc=GetDC(w);d.nSize=sizeof(d);d.nVersion=1;d.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL;d.iPixelType=PFD_TYPE_RGBA;d.cColorBits=32;pf=ChoosePixelFormat(dc,&d);if(!pf||!SetPixelFormat(dc,pf,&d))return 12;c=wglCreateContext(dc);if(!c||!wglMakeCurrent(dc,c))return 13;L(CS,cs,"glCreateShader");L(SS,ss,"glShaderSource");L(CO,co,"glCompileShader");L(SI,si,"glGetShaderiv");L(CP,cp,"glCreateProgram");L(AT,at,"glAttachShader");L(LI,li,"glLinkProgram");L(PI,pi,"glGetProgramiv");L(US,us,"glUseProgram");L(UL,ul,"glGetUniformLocation");L(UM,um,"glUniformMatrix4fv");L(GU,gu,"glGetUniformfv");L(DA,draw,"glDrawArrays");v=cs(VS);f=cs(FS);{const char*x=vs;ss(v,1,&x,0);}{const char*x=fs;ss(f,1,&x,0);}co(v);co(f);si(v,COMPILE,&ok);if(!ok)return 15;si(f,COMPILE,&ok);if(!ok)return 16;pr=cp();at(pr,v);at(pr,f);li(pr);pi(pr,LINK,&ok);if(!ok)return 17;us(pr);GLint loc=ul(pr,"transforms");if(loc<0)return 18;um(loc,2,GL_FALSE,matrices);GLfloat queried[32]={0};gu(pr,loc,queried);if(queried[0]!=1||queried[5]!=1||queried[16]!=2||queried[21]!=2)return 19;printf("WINEMETALGL_UNIFORM_MATRIX_ARRAY_OK\n");glViewport(0,0,64,64);draw(TRIANGLES,0,3);glReadPixels(32,32,1,1,GL_RGBA,GL_UNSIGNED_BYTE,px);printf("Uniform matrix rgba=%u,%u,%u,%u error=0x%x\n",px[0],px[1],px[2],px[3],(unsigned)glGetError());if(px[0]<47||px[0]>55||px[1]<98||px[1]>106||px[2]<149||px[2]>157||px[3]<250)return 20;printf("WINEMETALGL_UNIFORM_MATRIX_DRAW_OK\n");wglMakeCurrent(0,0);wglDeleteContext(c);ReleaseDC(w,dc);DestroyWindow(w);return 0;}
