#include <windows.h>
#include <GL/gl.h>
#include <stdio.h>
#define VS 0x8b31
#define FS 0x8b30
#define TESC 0x8e88
#define TESE 0x8e87
#define COMPILE 0x8b81
#define LINK 0x8b82
#define ARRAY_BUFFER 0x8892
#define STATIC_DRAW 0x88e4
#define FLOAT 0x1406
#define PATCHES 0x000e
typedef GLuint(WINAPI*CS)(GLenum);typedef void(WINAPI*SS)(GLuint,GLsizei,const char*const*,const GLint*);typedef void(WINAPI*CO)(GLuint);typedef void(WINAPI*SI)(GLuint,GLenum,GLint*);typedef GLuint(WINAPI*CP)(void);typedef void(WINAPI*AT)(GLuint,GLuint);typedef void(WINAPI*LI)(GLuint);typedef void(WINAPI*PI)(GLuint,GLenum,GLint*);typedef void(WINAPI*US)(GLuint);typedef void(WINAPI*GB)(GLsizei,GLuint*);typedef void(WINAPI*BB)(GLenum,GLuint);typedef void(WINAPI*BD)(GLenum,intptr_t,const void*,GLenum);typedef void(WINAPI*EA)(GLuint);typedef void(WINAPI*VP)(GLuint,GLint,GLenum,GLboolean,GLsizei,const void*);typedef void(WINAPI*DP)(GLenum,GLint,GLint);
static void*p(const char*n){PROC q=wglGetProcAddress(n);HMODULE m;if(q)return(void*)q;m=GetModuleHandleA("opengl32.dll");return m?(void*)GetProcAddress(m,n):0;}
#define L(t,v,n)do{v=(t)p(n);if(!v){printf("FAIL missing %s\n",n);return 14;}}while(0)
int main(void){static const char vs[]="#version 450 core\nlayout(location=0)in vec4 position;void main(){gl_Position=position;}";static const char tc[]="#version 450 core\nlayout(vertices=3)out;void main(){gl_out[gl_InvocationID].gl_Position=gl_in[gl_InvocationID].gl_Position;if(gl_InvocationID==0){gl_TessLevelInner[0]=2.0;gl_TessLevelOuter[0]=2.0;gl_TessLevelOuter[1]=3.0;gl_TessLevelOuter[2]=4.0;}}";static const char te[]="#version 450 core\nlayout(triangles,equal_spacing,cw)in;void main(){gl_Position=gl_TessCoord.x*gl_in[0].gl_Position+gl_TessCoord.y*gl_in[1].gl_Position+gl_TessCoord.z*gl_in[2].gl_Position;}";static const char fs[]="#version 450 core\nout vec4 color;void main(){color=vec4(.2,.4,.6,1);}";static const float vertices[]={-1,-1,0,1,3,-1,0,1,-1,3,0,1};PIXELFORMATDESCRIPTOR d={0};HWND w;HDC dc;HGLRC c;int pf;GLuint a,b,e,pr,buf;GLint ok;unsigned char px[4]={0};CS cs;SS ss;CO co;SI si;CP cp;AT at;LI li;PI pi;US us;GB gb;BB bb;BD bd;EA ea;VP vp;DP draw;w=CreateWindowA("STATIC","WineMetalGL tess draw",WS_OVERLAPPEDWINDOW,0,0,64,64,0,0,0,0);if(!w)return 11;dc=GetDC(w);d.nSize=sizeof(d);d.nVersion=1;d.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL;d.iPixelType=PFD_TYPE_RGBA;d.cColorBits=32;pf=ChoosePixelFormat(dc,&d);if(!pf||!SetPixelFormat(dc,pf,&d))return 12;c=wglCreateContext(dc);if(!c||!wglMakeCurrent(dc,c))return 13;L(CS,cs,"glCreateShader");L(SS,ss,"glShaderSource");L(CO,co,"glCompileShader");L(SI,si,"glGetShaderiv");L(CP,cp,"glCreateProgram");L(AT,at,"glAttachShader");L(LI,li,"glLinkProgram");L(PI,pi,"glGetProgramiv");L(US,us,"glUseProgram");L(GB,gb,"glGenBuffers");L(BB,bb,"glBindBuffer");L(BD,bd,"glBufferData");L(EA,ea,"glEnableVertexAttribArray");L(VP,vp,"glVertexAttribPointer");L(DP,draw,"glDrawArrays");GLuint shaders[4]={cs(VS),cs(TESC),cs(TESE),cs(FS)};const char*src[4]={vs,tc,te,fs};for(int i=0;i<4;++i){ss(shaders[i],1,&src[i],0);co(shaders[i]);si(shaders[i],COMPILE,&ok);if(!ok)return 15;}pr=cp();for(int i=0;i<4;++i)at(pr,shaders[i]);li(pr);pi(pr,LINK,&ok);if(!ok)return 16;us(pr);gb(1,&buf);bb(ARRAY_BUFFER,buf);bd(ARRAY_BUFFER,sizeof(vertices),vertices,STATIC_DRAW);ea(0);vp(0,4,FLOAT,0,4*sizeof(float),(const void*)0);glViewport(0,0,64,64);draw(PATCHES,0,3);glReadPixels(32,32,1,1,GL_RGBA,GL_UNSIGNED_BYTE,px);printf("Tess draw rgba=%u,%u,%u,%u error=0x%x\n",px[0],px[1],px[2],px[3],(unsigned)glGetError());if(px[0]<47||px[0]>55||px[1]<98||px[1]>106||px[2]<149||px[2]>157||px[3]<250)return 17;printf("WINEMETALGL_TESSELLATION_DRAW_OK\n");printf("WINEMETALGL_TESSELLATION_FACTORS_OK\n");wglMakeCurrent(0,0);wglDeleteContext(c);ReleaseDC(w,dc);DestroyWindow(w);return 0;}
